### ISSUE TITLE
validor script to make response curve from raw response histograms

### ISSUE THREAD

**Issue by jpata** [jpata/cmssw#10]
@juska would you be able to update the script https://github.com/jpata/cmssw/blob/pfvalidation/Validation/RecoParticleFlow/test/validor.py such that I can include it in a workflow that runs on top of an existing `DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root` file and updates it with the response scan plot? I believe you also need to commit the `Jet` class and other dependencies.
Thank you!

**Comment by jpata** [comment]
Would you be able to write a few lines in the readme how to run your script for the response curve on top of the DQM file? Thank you!
We should have smth like:

~~~
python test/addResponse.py DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO_withResponse.root
~~~

where the script `addResponse.py` loads all the histograms from `DQMData/Run 1/Physics/Run summary/JetResponse`

~~~
KEY: TH1F	reso_dist_1032_1248_eta05;1	Jet response (pT/pTgen) in 1032 <= pt < 1248, 0.0 <= |eta| < 0.5
KEY: TH1F	reso_dist_1032_1248_eta13;1	Jet response (pT/pTgen) in 1032 <= pt < 1248, 0.5 <= |eta| < 1.3
KEY: TH1F	reso_dist_1032_1248_eta21;1	Jet response (pT/pTgen) in 1032 <= pt < 1248, 1.3 <= |eta| < 2.1
KEY: TH1F	reso_dist_1032_1248_eta25;1	Jet response (pT/pTgen) in 1032 <= pt < 1248, 2.1 <= |eta| < 2.5
KEY: TH1F	reso_dist_1032_1248_eta30;1	Jet response (pT/pTgen) in 1032 <= pt < 1248, 2.5 <= |eta| < 3.0
KEY: TH1F	reso_dist_10_24_eta05;1	Jet response (pT/pTgen) in 10 <= pt < 24, 0.0 <= |eta| < 0.5
KEY: TH1F	reso_dist_10_24_eta13;1	Jet response (pT/pTgen) in 10 <= pt < 24, 0.5 <= |eta| < 1.3
KEY: TH1F	reso_dist_10_24_eta21;1	Jet response (pT/pTgen) in 10 <= pt < 24, 1.3 <= |eta| < 2.1
KEY: TH1F	reso_dist_10_24_eta25;1	Jet response (pT/pTgen) in 10 <= pt < 24, 2.1 <= |eta| < 2.5
KEY: TH1F	reso_dist_10_24_eta30;1	Jet response (pT/pTgen) in 10 <= pt < 24, 2.5 <= |eta| < 3.0
...
~~~
and produces a new TH1F `DQMData/Run 1/Physics/Run summary/JetResponse/total_response` that contains the data for the plot of pt vs `sigma(pT_reco/pT_gen)`.

**Comment by jpata** [comment]
@juska can you try your script on the DQM file attached to https://github.com/jpata/cmssw/issues/12#issuecomment-457425130?
If it works for you, we should incorporate your postprocessing step into the workflow. Thank you!

**Comment by juska** [comment]
Hi @jpata,

now that file works fine and I can plot the resolution, see the attachments.

I'm not sure which changes made it to the new file, but the resolution 
still seems bad w.r.t to what I get with validor.py.
It will probably get better once the matching is done as Chad told.

I will next fix the resolution plot code to work as you described, but 
this won't happen today sorry.

Have a nice weekend!

Juska

**Comment by juska** [comment]
Hi Joosep,

attached is a modified version of my plotting script, which now 
hopefully functions (almost) as you asked it to:

* It takes one argument - the path to the input file
* It creates TProfiles with (response scaled) resolution for each eta bin
* It writes the output to a file with the path 
"./input_file_name_addResponse.root"

What it does NOT do is copy the contents of the input file to the output 
file. I did not know how to do it, I can try to take a look tomorrow if 
you don't know how to do it easily. The error calculation also needs a 
small fix to be equivalent with the CMSSW version. I try to find the 
part from Chad's codes and implement it ASAP.

Sorry for not pushing this to Github but going old school with an 
attachment, it's just getting too late for the extra step.

Also, I'm sorry to tell that I can't contribute much this week, as I am 
attending a hardware service work related training, which is a full day 
thing for the rest of the week.

Cheers,

Juska

**Comment by jpata** [comment]
Thanks @juska ! The e-mail interface of github does not allow attachements so I don't have your code. If you have no time to commit it, can you share it using e.g. this tool https://gist.github.com?
PS: not sure if the existing plotting code in MultiTrackValidator supports TProfiles, hence it may be necessary to convert the final histogram to TH1D.

**Comment by jpata** [comment]
@hatakeyamak I'll work on including Juska's code for the pt-dependent response plot in the whole workflow and the web-plots. Physics-wise, the latest plots after running batch jobs are currently here: https://github.com/jpata/cmssw/issues/13
