### ISSUE TITLE
Script to make HTML pages and PDF plots more user-friendly 

### ISSUE THREAD

**Issue by jpata** [jpata/cmssw#12]
We use the script https://github.com/jpata/cmssw/blob/pfvalidation/Validation/RecoParticleFlow/test/compare.py
to create A vs B type comparison plots from `DQM*.root` files.

I'm working on creating a more convenient command line interface for that script, something along the lines of

~~~
./test/compare.py --sample QCD:DQMfile1.root:DQMfile2.root:DQMfile3.root --sample QCDNoPU:DQMfile4.root:DQMfile5.root:DQMfile6.root --plots JetResponse:reso_dist_10_24:reso_dist_10_24_eta05:reso_dist_10_24_eta13
~~~

would compare 3 versions of the sample QCD (DQMFile[1-3].root) and 3 versions of the sample QCDNoPu (DQMFile[4-6].root) and plot the histograms `reso_dist_10_24_eta05:reso_dist_10_24_eta13` from the folder `JetResponse` on a canvas `reso_dist_10_24`.

@hatakeyamak @juska would appreciate your thoughts.

**Comment by jpata** [comment]
@juska @hatakeyamak can you give a try if you find the interface usable by you? Attached is a DQM root file for testing.

[DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root.zip](https://github.com/jpata/cmssw/files/2794318/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root.zip)

**Comment by hatakeyamak** [comment]
Hey, Thanks. I will try.

**Comment by juska** [comment]
I'm now able to run the code without any problems by simply following the instructions in README, thanks a lot Joosep for the update! (I'm only in the reco processing step for now though)

I am waiting to hear back from Chad for hearing what is the 'official' match definition. If the deltaR requirement was something else than 0.2, that's one important fix. The convention is that it is half the cone size (or radius parameter in case of anti-kT), so we should have it at 0.2 as we have R=0.4 jets.
I'm surprised though that despite having the much looser matching condition the number of jets ending up to the response histograms was rather low (IIRC) - this could have to do with the matching.

I'll get back to you later today. I'll fix the pfreso.py to take the files as input and to spit out another file for the compare.py to use, and I'll try to see if I can recreate my nanoAOD resolution result with the DQM code.

**Comment by jpata** [comment]
Ah sorry, I had edited the script `run_relval.sh` script for the batch workflow but didn't test it with just the local workflow, which produces files with a slightly different name. Can you try again with https://github.com/jpata/cmssw/commit/94722fdda9a472777822c829f9ca21889da2d60d?

**Comment by jpata** [comment]
The comparison script now has the following default commandline interface
~~~

$ python test/compare.py --help
usage: compare.py [-h] -s SAMPLE [-p PLOTS] [--doResponsePlots]

optional arguments:
  -h, --help            show this help message and exit
  -s SAMPLE, --sample SAMPLE
                        DQM files to compare for a single sample, in the
                        format 'name:file1.root:file2.root:...:fileN.root'
  -p PLOTS, --plots PLOTS
                        Plots to put on a single canvas, in the format
                        'folder:name:plot1:plot2:...:plotN'
  --doResponsePlots     If enabled, do all jet response plots
~~~

and usage can be as simple as
~~~
$ python test/compare.py --sample FlatQCD:DQM1.root:DQM2.root--doResponsePlots
~~~
