### ISSUE TITLE
move from RECO -> MINIAOD in validation

### ISSUE THREAD

**Issue by jpata** [jpata/cmssw#15]
As @hatakeyamak suggested, we should do the validation on the CHS jets.

> I think it is better to deal with ak4 chs jets with default L1L2L3 corrections applied so that the response is first order already corrected.
Then, the resolution plot will be more sensitive to actual resolution effects, and less-dependent on non-uniformity of the response.

**Comment by jpata** [comment]
Switching to MINIAOD for the final comparison made it easier to run the batch jobs, about 47k events from 50k are finished within one day, here are the plots:
 
https://jpata.web.cern.ch/jpata/pfvalidation/2019_01_29/plots/

**Comment by hatakeyamak** [comment]
Sounds and looks good. But, I am curious. Why "Switching to MINIAOD for the final comparison made it easier to run the batch jobs,"??? when you are still re-running step3, and you are just using different outputs?

**Comment by hatakeyamak** [comment]
Aha, makes sense.

**Comment by jpata** [comment]
Solved, closing.
