### ISSUE TITLE
README crashes

### ISSUE THREAD

**Issue by juska** [jpata/cmssw#25]
The updated README.md crashes at the second command:

[juska@lxplus014 feb12]$ export SCRAM_ARCH=slc6_amd64_gcc700
[juska@lxplus014 feb12]$ cmsrel CMSSW_10_5_X_2019-01-31-1100
ERROR: Unable to find release area for "CMSSW" version "CMSSW_10_5_X_2019-01-31-1100" for arch slc6_amd64_gcc700.
       Please make sure you have used the correct name/version.
       You can run "scram list CMSSW" to get the list of available versions.
[juska@lxplus014 feb12]$

**Comment by jpata** [comment]
As we use CMSSW_10_5_X now, we have to track the development releases, which keep changing. At the moment CMSSW_10_5_0_pre1 has arrived which should stay longer on lxplus. I'm verifying with that.

**Comment by hatakeyamak** [comment]
Yeah, can you try to rebase to 10_5_0_pre1?
IB disappears too quickly.

**Comment by jpata** [comment]
Yeah, pre1 was not yet available when I first did the port from 9_4_X to 10_5_X. Now it is and I tested, it works fine. The new branch is https://github.com/jpata/cmssw/tree/pfvalidation-10_5_0_pre1-master. @Juska, please use that if you are making a PR. :)
