### ISSUE TITLE
'make plots' step crashes

### ISSUE THREAD

**Issue by juska** [jpata/cmssw#27]
After choosing an existing version of CMSSW and fixed overseas file reading with 'voms-proxy-init -voms cms', I successfully proceeded to the final plotting step but there I face the following error:

[juska@lxplus014 RecoParticleFlow]$ make plots
rm -Rf plots	
python test/compare.py --sample FlatQCD_noPU:tmp/QCD/DQMTotal.root:tmp/QCD/DQMTotal.root \
                --sample FlatQCD_PU25ns:tmp/QCDPU/DQMTotal.root:tmp/QCDPU/DQMTotal.root \
                --sample FlatQCD:tmp/QCD/DQMTotal.root:tmp/QCDPU/DQMTotal.root \
                --sample MinBias:tmp/MinBias/DQMTotal.root:tmp/MinBias/DQMTotal.root \
	--doResponsePlots
Trying to open DQM file tmp/QCD/DQMTotal.root for sample FlatQCD_noPU
Trying to open DQM file tmp/QCD/DQMTotal.root for sample FlatQCD_noPU
Trying to open DQM file tmp/QCDPU/DQMTotal.root for sample FlatQCD_PU25ns
Traceback (most recent call last):
  File "test/compare.py", line 139, in <module>
    main()
  File "test/compare.py", line 115, in main
    samples, plots = parse_args()
  File "test/compare.py", line 80, in parse_args
    name, files = parse_sample_string(ss)
  File "test/compare.py", line 29, in parse_sample_string
    raise Exception("Could not read DQM file {0}, it does not exist".format(fi))
Exception: Could not read DQM file tmp/QCDPU/DQMTotal.root, it does not exist
make: *** [Makefile:31: plots] Error 1
[juska@lxplus014 RecoParticleFlow]$

**Comment by juska** [comment]
I guess the tmp/QCDPU/DQMTotal.root file is never created

**Comment by jpata** [comment]
@juska, thanks for checking the recipe. Can you run the plots manually by adapting the call to compare.py? We still need to figure out how to run all the reco & dqm sequences reliably and fast with all stats.

**Comment by jpata** [comment]
You need to run all 4 samples (QCD, QCDPu, MinBias, ZMM) if you want to use the `make plots`. We won't be doing it via a makefile later on, as you need to submit batch/crab jobs.

**Comment by juska** [comment]
The readme has to be so that by carefully following the steps (and doing nothing else) every step works. I struggle to get comfortable with the tool because I have never managed to run the system without problems - let alone trying to develop some parts of it.

**Comment by juska** [comment]
> @juska, thanks for checking the recipe. Can you run the plots manually by adapting the call to compare.py? We still need to figure out how to run all the reco & dqm sequences reliably and fast with all stats.

I got it working with  "python test/compare.py --sample FlatQCD_noPU:tmp/QCD/DQMTotal.root:tmp/QCD/DQMTotal.root --doResponsePlots", so I can now try to polish the plots!

**Comment by jpata** [comment]
Good - thanks for the effort! The final recipe will certainly evolve to be more user friendly.
