### ISSUE TITLE
Move PFValidation development to new fork?

### ISSUE THREAD

**Issue by jpata** [jpata/cmssw#35]
@hatakeyamak @juska 
Now we used my personal CMSSW repo to develop the PFvalidation CMSSW code, but if we are generally happy with the direction, how about we move future developments to a new fork that is managed by the CMS PF group, not just me? We could set up a github organization (if it doesn't exist yet) similar as the BTV POG has done: https://github.com/cms-btv-pog

**Comment by hatakeyamak** [comment]
I probably personally perfer merging it to the central CMSSW.
It helps to keep track of potential necessary modifications due to releaese updates.

**Comment by jpata** [comment]
OK. So after the eventual merge to central CMSSW, any future updates to the PF/DQM code would also be done in private forks, followed up by central merges? I guess that's fine, too.

**Comment by hatakeyamak** [comment]
That's what I have in mind. We can make something like:
https://github.com/cms-btv-pog
but probably should wait until the re-organization is over.

**Comment by hatakeyamak** [comment]
I talked about this with @bendavid, and we thought, as long as the eventual developments go to CMSSW, we don't really need such group github. We can continue our current work scheme. Does it sound reasonable?

**Comment by jpata** [comment]
OK. I'm a little uncomfortable having central PF developments in my personal cmssw repo due to a possibility of mistakes, but as long as we don't nuke each others branches (like someone overwriting my master branch) it's ok.

**Comment by hatakeyamak** [comment]
Okay. I understand.

Well, apart from using your repo for issues, we can gradually move toward using our own repo. The first branch was highly collaborative and using your repo together was helpful, but from now on, I expect smaller incremental changes, so using a common repo won't be so necessary.

Thank you.
