### ISSUE TITLE
PFAlgo refactoring

### ISSUE THREAD

**Issue by jpata** [jpata/cmssw#56]
I made this issue to track the work on PFAlgo refactoring.

I'm now done with the first iteration of PF refactoring, PFAlgo::processBlock is broken up into subfunctions.

- [x] Factorize `PFAlgo::processBlock` to smaller subfunctions (https://github.com/cms-sw/cmssw/pull/27153 and https://github.com/cms-sw/cmssw/pull/26894)

The next steps are:

- [x] Follow up with a clang-format pass on the whole PFAlgo package
- [x] Modernize logging and make it thread-safe (cout -> MessageLogger)
- [ ] Sanitize the inputs and outputs of the functions and making sure they rely less on the PFAlgo state, each function ideally having a single purpose and clear inputs and outputs.
- [ ] Given the cleaned-up implementation from above, revisit the logic/physics of the algo to rewrite it from with Run3/HL-LHC in mind
- [ ] Compare to an eventual ML PF algo that arrives in CMS

I appreciate your inputs to this todo list.

One thing to note, I will be offline June 14 - 26. Therefore, if someone else such as @guitargeek want to do a few rounds of optimization, from my point of view this is a good time to avoid conflicts.

cc @hatakeyamak @bendavid

**Comment by guitargeek** [comment]
Thanks for the initiative and the summary, @jpata!

**Comment by hatakeyamak** [comment]
Have a good vacation. I will send you some thoughts/feedback over the next few days.

**Comment by hatakeyamak** [comment]
Coming back to this thread:
first of all, thanks for all you two do @jpata @guitargeek .

In the above list of Joosep, 
+ Follow up with a clang-format pass on the whole PFAlgo package
+ Modernize logging and make it thread-safe (cout -> MessageLogger)
are very clearly defined work, and sound good.

Beyond that would require algorithmic/conceptual developments which require deeper thoughts and planning. You might want to see the talk we gave at UPSG workshop yesterday:
https://indico.cern.ch/event/828365/

I think it will be also nice to add the utilization of the heterogeneous computing (e.g. GPU) for PF clustering and block producer if you are interested.

**Comment by jpata** [comment]
Very interesting slides, thanks for that. Clang-format has already been done, following up with logging and cleanup here: https://github.com/cms-sw/cmssw/pull/27505

I would like to invest some time in understanding the actual flow of the algorithm and the relevant datastructures once I get the logging updated. Even though PF is not a major CPU time consumer, it could be useful to think about PF on heterogeneous devices. In the past weeks I have been heavily involved in GPU programming for analysis.

**Comment by jpata** [comment]
I have now followed up on sanitizing the inputs and outputs of the some of the functions in PFAlgo a little bit in this PR: https://github.com/cms-sw/cmssw/pull/27901.

Overall, I'm now generally able to follow the logic of the code and mostly OK with it. Apart from completely rewriting `PFAlgo` from scratch given the physics goals, I don't foresee many fundamental changes at the moment that are easy to implement. As I'm not sure that this would be the highest priority item, I think it is a good moment to discuss what would be a good next step for the overall particle flow modernization project.

Possible options I see include:
- revisit PFBlockAlgo in a similar way
- start thinking about an ML-based and/or vectorizable PF algo

**Comment by hatakeyamak** [comment]
Thanks. Are Josh and Jonas getting messages in this thread?

In addition to what you have done, I am hoping to finish:
https://github.com/cms-sw/cmssw/pull/27782
as the config is a little mess, and some config parameters can be removed.

Apart from that, I don't have anything really concrete to work on, but a couple of questions and thoughts:

+ I am curious. Do you have any concrete ideas about "vectorize PF algo"?
+ I am still studying PFBlockProducer/linking in detail, so I don't have concrete ideas, but given that PFBlockProducer is the leading time-consumer for PF [1], I think it will be nice to see if there is a room for improvement in terms of cpu(gpu?) performance and physics performance.

@bendavid do you have some suggestions?

@jpata maybe you want to summarize what you have done so far, and potential options on what you may want to consider next in the next Tuesday's PF meeting?

[1] https://patatrack.web.cern.ch/patatrack/timing_report_june_2019/piechart.html

**Comment by jpata** [comment]
@hatakeyamak Thanks for your thoughts. I believe everyone who was mentioned here earlier should get the emails unless they explicitly disabled it. I can also send private emails but I find it useful to have a discussion in the open.

I will be happy to talk at the next PF meeting, I will prepare a few summary slides and thoughts.
