### ISSUE TITLE
particleFlow_cfi re-organization?

### ISSUE THREAD

**Issue by hatakeyamak** [jpata/cmssw#57]
Now, we have some on-going discussion to reoptimize PFEGammaFilters parameters to find an optimized balance between tau and egamma needs. Then, when I looked at relatively long particleFlow_cfi.py, I was wondering if we can re-organize to make it easier to work with.

For example, introduce PSets such as:
PFEGammaFiltersParam 
PFMuonAlgoParam
possibly also BadHcalTrackParam PSets
and put relevant parameter sets under them.

I think this will help egamma or muon people to focus only on parameters relevant for them.

Does this make sense? Is this something you can possibly look into? @guitargeek @jpata

Cc: @bendavid

**Comment by hatakeyamak** [comment]
By the way, I am puzzled why this line is necessary:
https://cmssdt.cern.ch/lxr/source/RecoParticleFlow/PFProducer/python/particleFlowEGamma_cff.py#0007
when RecoParticleFlow/PFProducer/python/particleFlowEGamma_cfi.py doesn't really exist any longer. [but I see that, if I remove this line, step3 doesn't run.]

**Comment by bendavid** [comment]
This file is automatically generated (by scram I think) based on the FillDescriptions in the corresponding C++ file.

**Comment by hatakeyamak** [comment]
I see.

https://github.com/hatakeyamak/cmssw/pull/new/Reconfigure_particleFlow_cfi
is the branch I created to take care of this. It also allowed me to spot a few config lines which are obsolete.

If it looks good to everybody here, I will make a PR tomorrow.
